# Generated by Django 6.0.1 on 2026-01-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketInstrumentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_code', models.CharField(db_index=True, max_length=64, verbose_name='КодИнструмента')),
                ('instrument_name', models.CharField(max_length=511, verbose_name='НаименованиеИнструмента')),
                ('delivery_basis', models.CharField(blank=True, max_length=128, null=True, verbose_name='БазисПоставки')),
                ('contracts_volume_ei', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='ОбъемДоговоровЕИ')),
                ('contracts_volume_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='ОбъемДоговоровРуб')),
                ('market_change_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='ИзмРынРуб')),
                ('market_change_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='ИзмРынПроц')),
                ('min_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='МинЦена')),
                ('avg_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='СреднЦена')),
                ('max_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='МаксЦена')),
                ('market_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='РынЦена')),
                ('best_offer', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='ЛучшПредложение')),
                ('best_bid', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='ЛучшСпрос')),
                ('contracts_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='КоличествоДоговоров')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('product', models.CharField(max_length=255, verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Единица торгов',
                'verbose_name_plural': 'Данные торгов',
                'constraints': [models.UniqueConstraint(fields=('instrument_code', 'instrument_name', 'date'), name='uq_instrument_date_product')],
            },
        ),
    ]
