# Generated by Django 6.0.1 on 2026-01-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ресурс')),
            ],
        ),
    ]
